name: cron

on:
  schedule:
    - cron: "1 1 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Create local changes
      run: |
        cd qotd && python generate.py
    - name: Commit files
      run: |
        git config --local user.email "daya_bot@gmail.com"
        git config --local user.name "daya0576(bot)"
        git add .
        git commit -m "Quote of the Day $(date +%Y-%m-%d)" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

